const nxPreset = require('@nx/jest/preset').default;

module.exports = {
  ...nxPreset,
  snapshotFormat: { escapeString: true, printBasicPrototype: true },
  coverageReporters: ['text', 'html'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    'index.ts',
    'main.ts',
    '.spec.ts',
    '.config.js',
    'route.ts',
    'layout.tsx',
    'types.ts',
    'type.ts',
    'utils.ts',
    '.d.ts',
  ],
  collectCoverageFrom: [
    '**/*.ts',
    '**/*.tsx',
    '**/*.js',
    '**/*.jsx',
    '!**/.next/**',
    '!**/jest.config.ts',
    '!**/eslint-rules/**',
    '!**/workspace-plugin/**',
    '!**/drizzle.config.ts/**',
    '!**/cors.ts/**',
    '!**/responses.ts/**',
    '!**/mockdata.ts/**',
    '!**/next-env.d.ts/**',
    '!**/schema.ts/**',
    '!**/relations.ts/**',
    '!**/cors.ts/**',
    '!**/drizzle.ts/**',
    '!**/redis.ts/**',
    '!**/club.schema.ts/**',
    '!**/timetable.schema.ts/**',
    '!**/*.js',
    '!**/*.jsx',
    '!**/.next/**',
    '!**/jest.config.ts',
    '!**/eslint-rules/**',
    '!**/libs/shadcn/**/*.tsx',
    '!**/*.d.ts',
    '!**/lib/utils.ts',
    '!**/graphql-codegen.yml',
    '!**/.vercel',
    '!**/.vercel/output/**/*.json',
    '!**/.vercel/output/**/*.js',
    '!**/*utils.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
};
