import type { ClubRequest } from "./Admin-Club-Types";

export const CLUB_REQUESTS: ClubRequest[] = [
  {
    id: 1,
    name: "React ",
    leader: "Б.Бат",
    status: "Шинэ",
    time: "14:00",
    room: "301",
    students: "15/20",
    repeat: "Weekly",
    goal: "React framework ашиглан бодит төсөл дээр ажиллах.",
  },
  {
    id: 2,
    name: "Java",
    leader: "Г.Тэмүүлэн",
    status: "Шинэ",
    time: "16:00",
    room: "305",
    students: "12/20",
    repeat: "Bi-weekly",
    goal: "Кибер аюулгүй байдлын үндсүүдийг судалж турших.",
  },
  {
    id: 3,
    name: "Leet code",
    leader: "А.Сарнай",
    status: "Шинэ",
    time: "15:30",
    room: "Studio 1",
    students: "20/20",
    repeat: "Weekly",
    goal: "UI/UX дизайн болон Figma дээрх прототайп хийх.",
  },
  {
    id: 4,
    name: "Interview ",
    leader: "Д.Дорж",
    status: "Шинэ",
    time: "10:00",
    room: "204",
    students: "10/15",
    repeat: "Monthly",
    goal: "Мэдээллийн сангийн зохиомж ба SQL хэл сурах.",
  },
  {
    id: 5,
    name: "Green",
    leader: "Ж.Болд",
    status: "Шинэ",
    time: "12:00",
    room: "101",
    students: "8/10",
    repeat: "Weekly",
    goal: "Python хэлний анхан шатны мэдлэг олгох.",
  },
];
