import './global.css';

export const metadata = {
  title: 'Welcome to club-web',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
