import { Club } from './types';

export const requests: Club[] = [
  {
    id: 1,
    name: 'React',
    leader: 'Б.Бат',
    time: '14:00',
    room: '301',
    students: '15/20',
    repeat: 'Weekly',
    goal: 'React framework ашиглан бодит төсөл дээр ажиллах.',
    status: 'approved',
  },
  {
    id: 2,
    name: 'Java',
    leader: 'Г.Тэмүүлэн',
    time: '16:00',
    room: '305',
    students: '12/20',
    repeat: 'Bi-weekly',
    goal: 'Кибер аюулгүй байдлын үндсүүдийг судалж турших.',
    status: 'approved',
  },
  {
    id: 3,
    name: 'Leet code',
    leader: 'А.Сарнай',
    time: '15:30',
    room: '402',
    students: '20/20',
    repeat: 'Weekly',
    goal: 'UI/UX дизайн болон Figma дээрх прототайп хийх.',
    status: 'approved',
  },
  {
    id: 4,
    name: 'Interview',
    leader: 'Д.Дорж',
    time: '10:00',
    room: '204',
    students: '10/15',
    repeat: 'Monthly',
    goal: 'Мэдээллийн сангийн зохиомж ба SQL хэл сурах.',
    status: 'pending',
  },
  {
    id: 5,
    name: 'Green',
    leader: 'Ж.Болд',
    time: '12:00',
    room: '101',
    students: '8/10',
    repeat: 'Weekly',
    goal: 'Python хэлний анхан шатны мэдлэг олгох.',
    status: 'pending',
  },
];

export const mockWeekdays = [
  { id: '1', day: 'M', value: 'MONDAY' },
  { id: '2', day: 'T', value: 'TUESDAY' },
  { id: '3', day: 'W', value: 'WEDNESDAY' },
  { id: '4', day: 'T', value: 'THURSDAY' },
  { id: '5', day: 'F', value: 'FRIDAY' },
  { id: '6', day: 'S', value: 'SATURDAY' },
  { id: '7', day: 'S', value: 'SUNDAY' },
];
