import { sqliteTable, AnySQLiteColumn, index, check, text, real, integer, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const students = sqliteTable("students", {
	id: text().primaryKey(),
	authUserId: text(),
	classId: text().notNull(),
	studentCode: text().notNull(),
	azureEmail: text().notNull(),
	registerNumber: text().notNull(),
	personalEmail: text(),
	profilePicture: text(),
	firstName: text(),
	lastName: text(),
	phoneNumber: text(),
	activeStatus: text().default("PENDING").notNull(),
	gender: text().default("OTHER"),
	profileProgress: real(),
	isGraduated: integer().default(0),
	isAdvocator: integer().default(0),
	isProfileVisible: integer().default(0),
	profileVisibledDate: text(),
	isProfileStaged: integer().default(0),
	isInternational: integer().default(0),
	dateOfBirth: text(),
	graduatedDate: text(),
	jobSeekingStatus: text(),
	hasAgreedTerms: integer().default(0),
	createdAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("student_code_idx").on(table.studentCode),
	index("student_phone_number_idx").on(table.phoneNumber),
	index("students_first_name_idx").on(table.firstName),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const classes = sqliteTable("classes", {
	id: text().primaryKey(),
	classNumber: text().notNull(),
	className: text().notNull(),
	classStartDate: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	classEndDate: text(),
	classStartTime: text(),
	classEndTime: text(),
	course: text().default("CODING").notNull(),
	teachers: text().default("sql`(json_array())`").notNull(),
	academicYearId: text(),
	isFinished: integer().default(0),
},
(table) => [
	index("class_course_idx").on(table.course),
	index("class_number_idx").on(table.classNumber),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const teachers = sqliteTable("teachers", {
	id: text().primaryKey(),
	email: text().notNull(),
	name: text().notNull(),
	phoneNumber: text(),
	profilePicture: text(),
	gender: text(),
	isActive: integer().default(1),
	createdAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("teacher_email_idx").on(table.email),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const classTeachers = sqliteTable("class_teachers", {
	id: text().primaryKey(),
	classId: text().notNull().references(() => classes.id, { onDelete: "cascade" } ),
	teacherId: text().notNull().references(() => teachers.id, { onDelete: "cascade" } ),
	assignedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("class_teacher_teacher_idx").on(table.teacherId),
	index("class_teacher_class_idx").on(table.classId),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const clubs = sqliteTable("clubs", {
	id: text().primaryKey(),
	creatorId: text(),
	name: text().notNull(),
	description: text(),
	teacherId: text(),
	minMember: integer(),
	maxMember: integer(),
	type: text().notNull(),
	preferredTeacher: text(),
	status: text().default("pending").notNull(),
	createdAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("club_teacher_idx").on(table.teacherId),
	index("club_type_idx").on(table.type),
	index("club_status_idx").on(table.status),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const clubMembers = sqliteTable("club_members", {
	id: text().primaryKey(),
	clubId: text().notNull().references(() => clubs.id, { onDelete: "cascade" } ),
	studentId: text().notNull().references(() => students.id, { onDelete: "cascade" } ),
	joinedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("club_members_student_idx").on(table.studentId),
	index("club_members_club_idx").on(table.clubId),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

export const timetable = sqliteTable("timetable", {
	id: text().primaryKey(),
	date: text().notNull(),
	clubStartTime: text(),
	clubEndTime: text(),
	room: integer(),
	duration: integer(),
	clubId: text().notNull().references(() => clubs.id, { onDelete: "cascade" } ),
	createdAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text().default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
(table) => [
	index("timetable_date_idx").on(table.date),
	index("timetable_club_idx").on(table.clubId),
	check("students_check_1", sql`activeStatus IN ('ACTIVE', 'ARCHIVED', 'PENDING', 'DROPOUT'`),
	check("students_check_2", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("students_check_3", sql`jobSeekingStatus IN ('READY', 'OPEN_TO_OFFER', 'UNAVAILABLE'`),
	check("classes_check_4", sql`course IN ('CODING', 'DESIGN'`),
	check("teachers_check_5", sql`gender IN ('FEMALE', 'MALE', 'OTHER'`),
	check("clubs_check_6", sql`type IN ('self', 'mentor'`),
	check("clubs_check_7", sql`status IN ('pending', 'approved', 'declined'`),
]);

